### PR TITLE
Add support for indexing transfer command

### LINKED ISSUE #23: Add support for indexing collection Transfer command
### Description

As a part of #1, we have to update streamer project to support the "Transfer" command of the collection module.

### Acceptance criteria

Service should be able to

    Index transactions of collection:transfer
    List collections with the latest updates
    Filter collections by
        collectionID
        creatorAddress
        offset
        count
    The above functionality must be tested (automated).

### PR DESCRIPTION
**Pull request by haghighatcs**
### What was the problem?
This PR resolves #23 

### How was it solved?

- [x] Index transactions
- [x] List Collections
- [x] Add filters
- [x] Change the owner of a collection by transfer command

### How was it tested?

- [x] Tested manually
- [x] Update unit test (if applicable)
- [x] Updated functional tests (if applicable)

### CODE REVIEW

**Review by curvesy — DISMISSED** [review]
Thank you Hamid, every thing is perfectly right.

**Review by curvesy — APPROVED** [review]
Thank you Hamid, every thing worked perfectly.

**Comment by haghighatcs** [comment]
LGTM

**Comment by haghighatcs** [comment]
LGTM

**Pull request merged**
